set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_C_FLAGS -O2)
set(CMAKE_CXX_FLAGS -O2)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)

find_program(_host_c_compiler NAMES gcc clang REQUIRED)
find_program(_host_cxx_compiler NAMES g++ clang++ REQUIRED)
set(CMAKE_C_COMPILER "${_host_c_compiler}")
set(CMAKE_CXX_COMPILER "${_host_cxx_compiler}")

if(NOT CMAKE_MAKE_PROGRAM)
    set(_android_sdk_roots "$ENV{ANDROID_HOME}" "$ENV{ANDROID_SDK_ROOT}")
    foreach(_android_sdk_root ${_android_sdk_roots})
        if(_android_sdk_root)
            file(GLOB _ninja_candidates "${_android_sdk_root}/cmake/*/bin/ninja")
            if(_ninja_candidates)
                list(SORT _ninja_candidates)
                list(REVERSE _ninja_candidates)
                list(GET _ninja_candidates 0 _ninja_path)
                set(CMAKE_MAKE_PROGRAM "${_ninja_path}" CACHE FILEPATH "Ninja used for host shader generation" FORCE)
                break()
            endif()
        endif()
    endforeach()
endif()
